// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTorrent(arg1) {
  return window['go']['main']['App']['AddTorrent'](arg1);
}

export function CastMediaToDevice(arg1, arg2) {
  return window['go']['main']['App']['CastMediaToDevice'](arg1, arg2);
}

export function DiscoverMovies(arg1, arg2, arg3) {
  return window['go']['main']['App']['DiscoverMovies'](arg1, arg2, arg3);
}

export function DiscoverShows(arg1, arg2, arg3) {
  return window['go']['main']['App']['DiscoverShows'](arg1, arg2, arg3);
}

export function GetActiveTorrents() {
  return window['go']['main']['App']['GetActiveTorrents']();
}

export function GetMediaDevices() {
  return window['go']['main']['App']['GetMediaDevices']();
}

export function GetMovieInfo(arg1, arg2) {
  return window['go']['main']['App']['GetMovieInfo'](arg1, arg2);
}

export function GetMovieTorrents(arg1, arg2) {
  return window['go']['main']['App']['GetMovieTorrents'](arg1, arg2);
}

export function GetShowInfo(arg1, arg2) {
  return window['go']['main']['App']['GetShowInfo'](arg1, arg2);
}

export function GetShowSeason(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetShowSeason'](arg1, arg2, arg3);
}

export function GetShowTorrents(arg1, arg2) {
  return window['go']['main']['App']['GetShowTorrents'](arg1, arg2);
}

export function GetSubtitles(arg1, arg2) {
  return window['go']['main']['App']['GetSubtitles'](arg1, arg2);
}

export function GetSubtitlesForEpisode(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetSubtitlesForEpisode'](arg1, arg2, arg3);
}

export function RemoveTorrent(arg1) {
  return window['go']['main']['App']['RemoveTorrent'](arg1);
}

export function SearchMovies(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchMovies'](arg1, arg2, arg3);
}

export function SearchShows(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchShows'](arg1, arg2, arg3);
}

export function StartMediaPlayer(arg1) {
  return window['go']['main']['App']['StartMediaPlayer'](arg1);
}
